extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  debug:
  file/spans:
    path: ./tmp/spans.json
  file/logs:
    path: ./tmp/logs.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [debug, file/spans]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [debug, file/logs]
  extensions: [memory_ballast, zpages, health_check]
