version: "3.7"
services:
  envoy-stats:
    build:
      context: .
      dockerfile: Dockerfile-zstd
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_ADMIN0:-9901}:9901"
    - "${PORT_ADMIN1:-9902}:9902"

  service:
    build:
      context: .
      dockerfile: Dockerfile-service
