version: "3.7"
services:

  flask:
    build:
      context: ../../shared/flask
    image: flask:python-3.10-slim-bullseye
    restart: "no"

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    ports:
    - "8002:8000"
    - "8003:8001"

  backend-service:
    image: flask:python-3.10-slim-bullseye
    volumes:
    - ./service.py:/code/service.py
