version: "3.8"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    depends_on:
      backend-service:
        condition: service_healthy
    ports:
    - "${PORT_BACKEND:-8002}:10000"
    - "${PORT_STATS:-8003}:8001"

  backend-service:
    build:
      context: ../../shared/flask
    volumes:
    - ./service.py:/code/service.py
