- hosts: all
  become: yes
  roles:
    - role: config-gcc
      gcc_version: 7
  tasks:
    - name: Build envoy
      shell:
        cmd: |
          echo "hello"
        chdir: '{{ zuul.project.src_dir }}'
        executable: /bin/bash
      environment: '{{ global_env }}'
