version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    networks:
      - envoymesh
    ports:
      - "8000:8000"

  web_service:
    build:
      context: .
      dockerfile: Dockerfile-web-service
    networks:
      - envoymesh
    ports:
      - "8080:80"

networks:
  envoymesh: {}
