language: cpp
sudo: required
services:
  - docker
install:
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=debug
  - TEST_TYPE=normal
  - TEST_TYPE=coverage
  - TEST_TYPE=asan
  - TEST_TYPE=docs
script: ./ci/ci_steps.sh

branches:
  only:
    - master
