static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.golang
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
              library_id: my-configurable-plugin-id
              library_path: "lib/my_configurable_plugin.so"
              plugin_name: my_configurable_plugin
              plugin_config:
                "@type": type.googleapis.com/xds.type.v3.TypedStruct
                value:
                  foo: default_foo
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: route_0
            virtual_hosts:
            - name: service_0
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster_0
                typed_per_filter_config:
                  envoy.filters.http.golang:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.ConfigsPerRoute
                    plugins_config:
                      my_configurable_plugin:
                        config:
                          "@type": type.googleapis.com/xds.type.v3.TypedStruct
                          value:
                            foo: vh_bar

  clusters:
  - name: cluster_0
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service.local
                port_value: 80
