version: "3.7"

services:

  wasm_compile_update:
    image: envoyproxy/envoy-build-ubuntu:9400637f4aa0232465407447bfda0d3da13549fb
    command: |
      bash -c "bazel build //examples/wasm-cc:envoy_filter_http_wasm_updated_example.wasm \
                && cp -a bazel-bin/examples/wasm-cc/* /build"
    working_dir: /source
    volumes:
      - ../..:/source
      - ./lib:/build

  wasm_compile:
    image: envoyproxy/envoy-build-ubuntu:9400637f4aa0232465407447bfda0d3da13549fb
    command: |
      bash -c "bazel build //examples/wasm-cc:envoy_filter_http_wasm_example.wasm \
                && cp -a bazel-bin/examples/wasm-cc/* /build"
    working_dir: /source
    volumes:
      - ../..:/source
      - ./lib:/build
