version: '2'
services:

  front-envoy:
    build:
      context: ..
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"

  service:
    build:
      context: ..
      dockerfile: samesite/Dockerfile-service
    volumes:
      - ../service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service
    expose:
      - "8000"

networks:
  envoymesh: {}
