version: "3.7"
services:

  # base images
  flask:
    build:
      context: ../shared/flask
    image: flask:python-3.10-slim-bullseye
    restart: "no"

  tracing:
    build:
      context: ../shared/tracing
    image: envoyproxy:tracing
    restart: "no"

  # zipkin
  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    ports:
    - "8000:8000"

  service1:
    image: envoyproxy:tracing
    volumes:
    - ./service1-envoy-zipkin.yaml:/etc/service-envoy.yaml
    environment:
    - SERVICE_NAME=1

  service2:
    image: envoyproxy:tracing
    volumes:
    - ./service2-envoy-zipkin.yaml:/etc/service-envoy.yaml
    environment:
    - SERVICE_NAME=2

  zipkin:
    image: openzipkin/zipkin
    ports:
    - "9411:9411"
