admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: localhost-listener
    address:
      socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 7777
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: admin_cluster
          http_filters:
          - name: rbac-deny-if-custom-team-is-swg
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
              rules:
                action: DENY
                custom_library_config:
                  name: envoy.rbac.custom_library_config.custom_library
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.rbac.custom_library_config.v3.CustomLibraryConfig
                    replace_default_library_in_case_of_overlap: false
                policies:
#                  "policy-rbac-deny-if-custom-team-is-swg":
#                    # deny if custom[team].equals("swg")
#                    condition:
#                      call_expr:
#                        function: contains
#                        args:
#                        - select_expr:
#                            operand:
#                              ident_expr:
#                                name: custom
#                            field: team
#                        - const_expr:
#                            string_value: swg
#                    permissions:
#                    - any: true
#                    principals:
#                    - any: true
                  "policy-rbac-deny-if-lazy-func-returns-99":
                    # deny if LazyConstFuncReturns99() == 99
                    condition:
                      call_expr:
                        function: _==_
                        args:
                        - call_expr:
                            function: LazyConstFuncReturns99
                        - const_expr:
                            int64_value: 99
                    permissions:
                    - any: true
                    principals:
                    - any: true
#                  "policy-deny-if-eager-func-returns-99":
#                    # deny if EagerConstFuncReturns99(1) == 99
#                    condition:
#                      call_expr:
#                        function: _==_
#                        args:
#                        - call_expr:
#                            function: EagerConstFuncReturns99
#                            args:
#                            - const_expr:
#                                int64_value: 1
#                        - const_expr:
#                            int64_value: 99
#                    permissions:
#                    - any: true
#                    principals:
#                    - any: true
#                  "policy-rbac-deny-if-ip-is-localhost":
#                    # deny if custom[ip].equals("127.0.0.1")
#                    condition:
#                      call_expr:
#                        function: _==_
#                        args:
#                        - select_expr:
#                            operand:
#                              ident_expr:
#                                name: custom
#                            field: ip
#                        - const_expr:
#                            string_value: 127.0.0.1
#                    permissions:
#                    - any: true
#                    principals:
#                    - any: true
          - name: envoy.filters.http.router
  clusters:
  - name: admin_cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: admin_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9901
