version: "3.8"
services:

  flask_service:
    build:
      context: ../shared/flask
    image: flask_service:python-3.10-slim-bullseye
    restart: "no"
    deploy:
      replicas: 0

  envoy-stats:
    build:
      context: .
      dockerfile: Dockerfile-gzip
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_STATS0:-9901}:9901"
    - "${PORT_STATS1:-9902}:9902"

  service:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
    - ./service.py:/code/service.py
