name: android_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kotlintestsmac:
    name: kotlin_tests_mac
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - run: |
          bazelisk test --test_output=all --build_tests_only //test/kotlin/...
        name: 'Run Kotlin library tests'
  javatestsmac:
    name: java_tests_mac
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - run: |
          bazelisk test --test_output=all --build_tests_only  //test/java/...
        name: 'Run Java library tests'
  kotlintestslinux:
    # Only kotlin tests are executed since with linux:
    # https://github.com/envoyproxy/envoy-mobile/issues/1418.
    name: kotlin_tests_linux
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:e33c93e6d79804bf95ff80426d10bdcc9096c785
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: |
          bazel test --test_output=all --build_tests_only //test/kotlin/...
        name: 'Run Kotlin library integration tests'
