name: android

on: [push]

jobs:
  linuxdist:
    name: linux_dist
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Build envoy.aar distributable'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          ./bazelw build --fat_apk_cpu=x86 //:android_dist
    # TODO: parallelize these two jobs
      - name: 'Build Java app'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          ./bazelw build --fat_apk_cpu=x86 //examples/java/hello_world:hello_envoy
      - name: 'Build kotlin app'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          ./bazelw build --fat_apk_cpu=x86 //examples/kotlin/hello_world:hello_envoy_kt
  macdist:
    name: mac_dist
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - name: 'Build envoy.aar distributable'
        run: ./bazelw build --fat_apk_cpu=x86 //:android_dist
      - uses: actions/upload-artifact@v1
        with:
          name: envoy.aar
          path: dist/envoy.aar
  macjava:
    name: mac_java_helloworld
    needs: macdist
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - uses: actions/download-artifact@v1
        with:
          name: envoy.aar
          path: dist/
      - run: ls -lh dist/
      - name: start simulator
        run: ./ci/mac_start_simulator.sh
      - run: ./bazelw mobile-install --fat_apk_cpu=x86 --start_app //examples/java/hello_world:hello_envoy
        name: 'Start java app'
      - run: 'adb logcat -e "successful response!" -m 1'
        name: 'Check liveliness'
  mackotlin:
    name: mac_kotlin_helloworld
    needs: macdist
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - uses: actions/download-artifact@v1
        with:
          name: envoy.aar
          path: dist/
      - run: ls -lh dist/
      - name: start simulator
        run: ./ci/mac_start_simulator.sh
      - run: ./bazelw mobile-install --fat_apk_cpu=x86 --start_app //examples/kotlin/hello_world:hello_envoy_kt
        name: 'Start kotlin app'
      - run: 'adb logcat -e "successful response!" -m 1'
        name: 'Check liveliness'
  kotlintests:
    name: kotlin_tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - run: ./bazelw test --test_output=all --build_tests_only //library/kotlin/test/...
        name: 'Run Kotlin library tests'
