name: android_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kotlintestsmac:
    name: kotlin_tests_mac
    runs-on: macos-11
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e java/ -e kotlin/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/android_tests.yml$ ; then
            echo "Tests will run."
            echo "::set-output name=run_tests::true"
          else
            echo "Skipping tests."
            echo "::set-output name=run_tests::false"
          fi
      - name: 'Java setup'
        if: steps.check_context.outputs.run_tests == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: 'Install dependencies'
        if: steps.check_context.outputs.run_tests == 'true'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run Kotlin library tests'
        if: steps.check_context.outputs.run_tests == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bazel test \
            --test_output=all \
            --build_tests_only \
            --config=remote-ci-macos \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/kotlin/...
  javatestsmac:
    name: java_tests_mac
    runs-on: macos-11
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e java/ -e kotlin/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/android_tests.yml$ ; then
            echo "Tests will run."
            echo "::set-output name=run_tests::true"
          else
            echo "Skipping tests."
            echo "::set-output name=run_tests::false"
          fi
      - name: 'Java setup'
        if: steps.check_context.outputs.run_tests == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: 'Install dependencies'
        if: steps.check_context.outputs.run_tests == 'true'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run Java library tests'
        if: steps.check_context.outputs.run_tests == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bazel test \
            --test_output=all \
            --build_tests_only \
            --config=remote-ci-macos \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            --define=signal_trace=disabled \
            //test/java/...
  kotlintestslinux:
    # Only kotlin tests are executed since with linux:
    # https://github.com/envoyproxy/envoy-mobile/issues/1418.
    name: kotlin_tests_linux
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:b51ac7a0f2cb5dd729984a379a301ce029ac765d
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e java/ -e kotlin/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/android_tests.yml$ ; then
            echo "Tests will run."
            echo "::set-output name=run_tests::true"
          else
            echo "Skipping tests."
            echo "::set-output name=run_tests::false"
          fi
      - name: 'Java setup'
        if: steps.check_context.outputs.run_tests == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: 'Run Kotlin library integration tests'
        if: steps.check_context.outputs.run_tests == 'true'
        run: |
          bazel test --test_output=all --build_tests_only //test/kotlin/...
