name: artifacts

on:
  push:
    branches:
      - master
    paths:
      - 'library/common/**'
      - 'library/java/**'
      - 'library/kotlin/**'
      - 'envoy/**'

jobs:
  master_aar_dist:
    name: master_aar_dist
    runs-on: macOS-10.14
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - name: 'Build envoy_master.aar distributable'
        run: ./bazelw build --config=release --fat_apk_cpu=x86,armeabi-v7a,arm64-v8a //:android_dist
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_master.zip
          path: dist/envoy.aar
