name: asan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  asan:
    name: asan
    runs-on: ubuntu-18.04
    timeout-minutes: 180
    container:
      image: envoyproxy/envoy-build-ubuntu:8ca107a75ee98b255aa59db2ab40fd0800a3ce99
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/asan.yml$ ; then
            echo "Tests will run."
            echo "::set-output name=run_tests::true"
          else
            echo "Skipping tests."
            echo "::set-output name=run_tests::false"
          fi
      - uses: actions/setup-java@v1
        if: steps.check-cache.outputs.cache-hit != 'true'
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: 'Run tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_context.outputs.run_tests == 'true'
        run: |
          ./bazelw test --test_output=all \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            --config=remote-ci-linux-asan \
            //test/common/...
