name: core

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unittests:
    name: unit_tests
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run tests'
        run: bazel test --test_output=all //test/...
  tsan:
    name: tsan
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Run tests'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          bazel test --config=clang-tsan --test_output=all //test/...
  asan:
    name: asan
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Run tests'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          bazel test --config=clang-asan --test_output=all //test/...
