name: core

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittests:
    name: unit_tests
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run tests'
        run: bazelisk test --test_output=all //test/...
  tsan:
    name: tsan
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:11efa5680d987fff33fde4af3cc5ece105015d04
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: echo $PATH
      - name: 'Run tests'
        run: bazel test --config=clang-tsan --test_output=all --test_env=ENVOY_IP_TEST_VERSIONS=v4only //test/...
  asan:
    name: asan
    runs-on: ubuntu-18.04
    timeout-minutes: 180
    container:
      image: envoyproxy/envoy-build-ubuntu:11efa5680d987fff33fde4af3cc5ece105015d04
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run tests'
        run: bazel test --config=clang-asan --test_output=all --test_env=ENVOY_IP_TEST_VERSIONS=v4only //test/...
