name: format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatall:
    name: format_all
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    container:
      image: envoyproxy/envoy-build-ubuntu:3f6b1b096f2c0652ed270c5564b292bdd9a520f6
      env:
        CLANG_FORMAT: /opt/llvm/bin/clang-format
        BUILDIFIER_BIN: /usr/local/bin/buildifier
        BUILDOZER_BIN: /usr/local/bin/buildozer
        ENVOY_BAZEL_PREFIX: "@envoy"
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run formatters'
        run: ./tools/check_format.sh
  precommit:
    name: precommit
    runs-on: macos-12
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
      - name: 'Install precommit'
        run: brew install pre-commit
      - name: 'Run precommit'
        run: pre-commit run --all-files
  swiftlint:
    name: swift_lint
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    container:
      image: ghcr.io/realm/swiftlint:0.47.1
    steps:
      - uses: actions/checkout@v1
      - name: 'Run Swift Lint (SwiftLint)'
        run: swiftlint lint --strict
  drstring:
    name: drstring
    runs-on: macos-12
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run DrString'
        run: ./bazelw run @DrString//:drstring check
  kotlinlint:
    name: kotlin_lint
    runs-on: macos-12
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - name: 'Run Kotlin Lint (Detekt)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw build \
            --config=remote-ci-macos --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //library/kotlin/io/envoyproxy/envoymobile:envoy_lib_lint \
            //examples/kotlin/hello_world:hello_envoy_kt_lint
      - name: 'Run Kotlin Formatter (ktlint)'
        run: |
          ./bazelw build kotlin_format
