name: ios

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  macdist:
    name: mac_dist
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build Envoy.framework distributable'
        run: bazel build --config=ios //:ios_dist
      - name: 'Zip Envoy.framework.zip distributable'
        run: zip -r dist/Envoy.framework.zip dist/Envoy.framework
      - run: ls -lh dist/
      - uses: actions/upload-artifact@v1
        with:
          name: Envoy.framework.zip
          path: dist/Envoy.framework.zip
  macswift:
    name: mac_swift_helloworld
    needs: macdist
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v1
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build swift app'
        run: bazel build --config=ios //examples/swift/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run swift app'
        run: bazel run --config=ios //examples/swift/hello_world:app &> /tmp/envoy.log &
      - name: 'Wait for simulator to start & perform requests'
        run: sleep 180
      # Print out the log in case the liveliness check fails.
      # This allows the author to decide if the failure is a flake or a real problem.
      - name: 'Cat log'
        run: 'cat /tmp/envoy.log'
      # Check for the sentinel value that shows the app is alive and well.
      - name: 'Check liveliness'
        run: 'cat /tmp/envoy.log | grep "received headers with status 200"'
  macobjc:
    name: mac_objc_helloworld
    needs: macdist
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v1
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build objective-c app'
        run: bazel build --config=ios //examples/objective-c/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run objective-c app'
        run: bazel run --config=ios //examples/objective-c/hello_world:app &> /tmp/envoy.log &
      - name: 'Wait for simulator to start & perform requests'
        run: sleep 180
      # Print out the log in case the liveliness check fails.
      # This allows the author to decide if the failure is a flake or a real problem.
      - name: 'Cat log'
        run: 'cat /tmp/envoy.log'
      # Check for the sentinel value that shows the app is alive and well.
      - name: 'Check liveliness'
        run: 'cat /tmp/envoy.log | grep "received headers with status 200"'
  swifttests:
    name: swift_tests
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run swift library tests'
        run: bazel test --test_output=all --config=ios --build_tests_only //library/swift/test/...
