name: ios_build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  iosbuild:
    name: ios_build
    runs-on: macOS-latest
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v2
        id: check-cache
        with:
          key: framework-${{ github.sha }}
          path: dist/Envoy.framework
        name: 'Check cache'
      - run: echo "Found Envoy.framework from previous run!"
        if: steps.check-cache.outputs.cache-hit == 'true'
        name: 'Build cache hit'
      - run: ./ci/mac_ci_setup.sh
        if: steps.check-cache.outputs.cache-hit != 'true'
        name: 'Install dependencies'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bazelisk shutdown
          bazelisk build --config=ios --config=remote-ci-macos --remote_header="Authorization=Bearer $GITHUB_TOKEN" //:ios_dist
        if: steps.check-cache.outputs.cache-hit != 'true'
        name: 'Build Envoy.framework distributable'
  swifthelloworld:
    name: swift_helloworld
    needs: iosbuild
    runs-on: macOS-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - uses: actions/cache@v2
        id: check-cache
        with:
          key: framework-${{ github.sha }}
          path: dist/Envoy.framework
        name: 'Download framework'
      - run: exit 1
        if: steps.check-cache.outputs.cache-hit != 'true'
        name: 'Short-circuit'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bazelisk build --config=ios --config=remote-ci-macos --remote_header="Authorization=Bearer $GITHUB_TOKEN" //examples/swift/hello_world:app
        name: 'Build swift app'
      # Run the app in the background and redirect logs.
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bazelisk run --config=ios --config=remote-ci-macos --remote_header="Authorization=Bearer $GITHUB_TOKEN" //examples/swift/hello_world:app &> /tmp/envoy.log &
        name: 'Run swift app'
      - run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
        name: 'Check connectivity'
      - run: cat /tmp/envoy.log
        if: ${{ failure() || cancelled() }}
        name: 'Log app run'
  objchelloworld:
    name: objc_helloworld
    needs: iosbuild
    runs-on: macOS-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - uses: actions/cache@v2
        id: check-cache
        with:
          key: framework-${{ github.sha }}
          path: dist/Envoy.framework
        name: 'Download framework'
      - run: exit 1
        if: steps.check-cache.outputs.cache-hit != 'true'
        name: 'Short-circuit'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bazelisk build --config=ios --config=remote-ci-macos --remote_header="Authorization=Bearer $GITHUB_TOKEN" //examples/objective-c/hello_world:app
        name: 'Build objective-c app'
      # Run the app in the background and redirect logs.
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bazelisk run --config=ios --config=remote-ci-macos --remote_header="Authorization=Bearer $GITHUB_TOKEN" //examples/objective-c/hello_world:app &> /tmp/envoy.log &
        name: 'Run objective-c app'
      - run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
        name: 'Check connectivity'
      - run: cat /tmp/envoy.log
        if: ${{ failure() || cancelled() }}
        name: 'Log app run'
