on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * 1,2,3,4,5'

jobs:
  pr_notifier:
    name: PR Notifier
    runs-on: ubuntu-latest
    if: github.repository_owner == 'envoyproxy'

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/actions/pr_notifier/requirements.txt
    - name: Notify about PRs
      run: python ./.github/actions/pr_notifier/pr_notifier.py --cron_job
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
