name: tsan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tsan:
    name: tsan
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:0a02a76af5951bf7f4c7029c0ea6d29d96c0f682
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Add safe directory
        run: git config --global --add safe.directory /__w/envoy-mobile/envoy-mobile
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/tsan.yml$ ; then
            echo "Tests will run."
            echo "::set-output name=run_tests::true"
          else
            echo "Skipping tests."
            echo "::set-output name=run_tests::false"
          fi
      - uses: actions/setup-java@v1
        if: steps.check-cache.outputs.cache-hit != 'true'
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: 'Run tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_context.outputs.run_tests == 'true'
        run: |
          ./bazelw test \
            --test_output=all \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-tsan") \
            //test/common/...
