version: "3.7"

services:

  # Requires the build of the stubs first
  grpc-server:
    image: envoyproxy/example-kv-server
    build:
      context: server
    ports:
      - "8081:8081"
    networks:
      envoymesh:
        aliases:
          - kv-backend-service

  grpc-server-proxy:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      envoymesh:
        aliases:
          - kv-backend-proxy
    ports:
      - "8811:8811"

  # Requires the build of the stubs first
  grpc-client:
    image: envoyproxy/example-kv-client
    build:
      context: client
    environment:
      - CLIENT_PROXY=http://kv-client-proxy:9911
    networks:
      - envoymesh

  grpc-client-proxy:
    build:
      context: .
      dockerfile: Dockerfile-client
    networks:
      envoymesh:
        aliases:
          - kv-client-proxy
    ports:
      - "9911:9911"

networks:
  envoymesh: {}
