version: '3.7'
services:

  flask:
    build:
      context: ../shared/flask
    image: flask:python-3.10-slim-bullseye
    restart: "no"

  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    ports:
    - "80-81:80"
    - "8081:8081"

  http_service:
    image: flask:python-3.10-slim-bullseye
    volumes:
    - ./service.py:/code/service.py

  lrs_server:
    build:
      context: .
      dockerfile: Dockerfile-lrs
    volumes:
    - /go/src/github.com/envoyproxy/envoy/examples/load-reporting-service
    ports:
    - "18000:18000"
