trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - 'v*'

# PR build config is manually overridden in Azure pipelines UI with different secrets
pr: none

jobs:
- job: format
  dependsOn: [] # this removes the implicit dependency on previous stage and causes this to run in parallel.
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: CacheBeta@1
    inputs:
      key: 'format | ./WORKSPACE | **/*.bzl'
      path: $(Build.StagingDirectory)/repository_cache

  - script: ci/run_envoy_docker.sh 'ci/check_and_fix_format.sh'
    workingDirectory: $(Build.SourcesDirectory)
    env:
      ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
    displayName: "Run check format scripts"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.StagingDirectory)/fix_format.diff"
      artifactName: format
    condition: failed()

- job: bazel
  dependsOn: ["format"]
  # For master builds, continue even if format fails
  condition: or(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  strategy:
    maxParallel: 3
    matrix:
      release:
        CI_TARGET: 'bazel.release'
      asan:
        CI_TARGET: 'bazel.asan'
      tsan:
        CI_TARGET: 'bazel.tsan'
      clang_tidy:
        CI_TARGET: 'bazel.clang_tidy'
      gcc:
        CI_TARGET: 'bazel.gcc'
      compile_time_options:
        CI_TARGET: 'bazel.compile_time_options'
      # This will run on every commit/PR and will make sure the corpus generated by the fuzzers as well as fixed crashes
      # (on Fuzzit) is not crashing envoy. This will help find bugs BEFORE merging and not after.
      fuzzit:
        CI_TARGET: 'bazel.fuzzit'
  timeoutInMinutes: 360
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: CacheBeta@1
    inputs:
      key: '"$(CI_TARGET)" | ./WORKSPACE | **/*.bzl'
      path: $(Build.StagingDirectory)/repository_cache

  - bash: |
      echo "disk space at beginning of build:"
      df -h
    displayName: "Check disk space at beginning"

  - bash: |
      sudo mkdir -p /etc/docker
      echo '{
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }' | sudo tee /etc/docker/daemon.json
      sudo service docker restart
    displayName: "Enable IPv6"

  - script: ci/run_envoy_docker.sh 'ci/do_ci.sh $(CI_TARGET)'
    workingDirectory: $(Build.SourcesDirectory)
    env:
      ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
      ENVOY_RBE: "true"
      BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-ci --config=remote --jobs=$(RbeJobs) --curses=no"
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
    displayName: "Run CI script"

  - bash: |
      echo "disk space at end of build:"
      df -h
    displayName: "Check disk space at end"
    condition: always()

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/bazel-out/**/testlogs/**/test.xml'
      testRunTitle: '$(CI_TARGET)'
      searchFolder: $(Build.StagingDirectory)/tmp
    condition: always()

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.StagingDirectory)/envoy"
      artifactName: $(CI_TARGET)
    condition: always()

- job: docker
  dependsOn: ["bazel"]
  condition: and(succeeded(), eq(variables['PostSubmit'], 'true'), ne(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      artifactName: "bazel.release"
      itemPattern: "bazel.release/envoy_binary.tar.gz"
      downloadType: single
      targetPath: $(Build.StagingDirectory)

  - bash: |
      set -e
      tar zxf $(Build.StagingDirectory)/bazel.release/envoy_binary.tar.gz
      ci/docker_build.sh
      ci/docker_push.sh
      ci/docker_tag.sh
    workingDirectory: $(Build.SourcesDirectory)
    env:
      AZP_BRANCH: $(Build.SourceBranch)
      CIRCLE_SHA1: $(Build.SourceVersion)
      DOCKERHUB_USERNAME: $(DockerUsername)
      DOCKERHUB_PASSWORD: $(DockerPassword)
