name: Envoy CI

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      rbe:
        type: boolean
        default: true
      managed:
        type: boolean
        default: true

      auth_bazel_rbe:
        type: string
        default: ''

      bazel_extra:
        type: string
        default:
      bazel_local_cache:
        type: string
        default:
      bazel_rbe_cache:
        type: string
        default: grpcs://remotebuildexecution.googleapis.com
      bazel_rbe_instance:
        type: string
        default: projects/envoy-ci/instances/default_instance
      bazel_rbe_jobs:
        type: number
        default: 75

      cache_build_image:
        type: string

      command_prefix:
        type: string
        default: ./ci/run_envoy_docker.sh
      command_ci:
        type: string
        default: ./ci/do_ci.sh

      diskspace_hack:
        type: boolean
        default: false

      run_pre:
        type: string
        default:
      run_pre_with:
        type: string
        default:

      run_post:
        type: string
        default:
      run_post_with:
        type: string
        default:

      skip:
        type: boolean
        default: false

      env:
        type: string

concurrency:
  group: ${{ github.head_ref || github.run_id }}-ci-${{ inputs.target }}
  cancel-in-progress: true

jobs:
  do_ci:
    if: ${{ ! inputs.skip }}
    runs-on: ubuntu-22.04
    name: do_ci.sh ${{ inputs.target }}
    steps:
    - if: ${{ inputs.cache_build_image }}
      uses: envoyproxy/toolshed/gh-actions/docker/cache/restore@actions-v0.0.10
      with:
        image_tag: ${{ inputs.cache_build_image }}
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy

    - if: ${{ inputs.diskspace_hack }}
      name: Cruft removal
      run: |
        echo "Disk space before cruft removal"
        df -h

        TO_REMOVE=(
            /opt/hostedtoolcache
            /usr/local/lib/android
            /usr/local/.ghcup)

        for removal in "${TO_REMOVE[@]}"; do
            echo "Removing: ${removal} ..."
            sudo rm -rf "$removal"
        done
    - run: |
        echo "disk space at beginning of build:"
        df -h
      name: "Check disk space at beginning"

    - if: ${{ inputs.run_pre }}
      uses: envoyproxy/toolshed/gh-actions/using/recurse@actions-v0.0.10
      with:
        uses: ${{ inputs.run_pre }}
        with: ${{ inputs.run_pre_with }}

    - uses: ./.github/actions/do_ci
      with:
        target: ${{ inputs.target }}
        rbe: ${{ inputs.rbe }}
        managed: ${{ inputs.managed }}
        auth_bazel_rbe: ${{ inputs.auth_bazel_rbe }}
        bazel_extra: ${{ inputs.bazel_extra }}
        bazel_local_cache: ${{ inputs.bazel_local_cache }}
        bazel_rbe_cache: ${{ inputs.bazel_rbe_cache }}
        bazel_rbe_instance: ${{ inputs.bazel_rbe_instance }}
        bazel_rbe_jobs: ${{ inputs.bazel_rbe_jobs }}
        command_prefix: ${{ inputs.command_prefix }}
        command_ci: ${{ inputs.command_ci }}
        env: ${{ inputs.env }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - if: ${{ inputs.run_post }}
      uses: envoyproxy/toolshed/gh-actions/using/recurse@actions-v0.0.10
      with:
        uses: ${{ inputs.run_post }}
        with: ${{ inputs.run_post_with }}

    - run: |
        echo "disk space at end of build:"
        df -h
        echo
        du -ch "${{ runner.temp }}" | grep -E "[0-9]{2,}M|[0-9]G"
      name: "Check disk space at end"
