name: Environment

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      # Authoritative configuration for build image/s
      build_image_repo:
        type: string
        default: envoyproxy/envoy-build-ubuntu
      build_image_sha:
        type: string
        default: 3c8a3ce6f90dcfb5d09dc8f79bb01404d3526d420061f9a176e0a8e91e1e573e
      build_image_mobile_sha:
        type: string
        default: f47fb698cfda583769b9d28e8d1c58cfc7774d5da4f31cd8190d8975c3850c7e
      # this is authoritative, but is not currently used in github ci
      build_image_gcr_sha:
        type: string
        default: 2a473cd9808182735d54e03b158975389948b9559b8e8fc624cfafbaf7059e62
      build_image_tag:
        type: string
        default: fdd65c6270a8507a18d5acd6cf19a18cb695e4fa

      check_mobile_run:
        type: boolean
        default: true
      prime_build_image:
        type: boolean
        default: false

      repo_ref:
        type: string
        default:
      repo_ref_sha:
        type: string
        default:
      repo_ref_name:
        type: string
        default:

    outputs:
      debug:
        value: false
      agent_ubuntu:
        value: ubuntu-22.04
      build_image_ubuntu:
        value: ${{ jobs.repo.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile:
        value: ${{ jobs.repo.outputs.build_image_ubuntu_mobile }}
      mobile_android_build:
        value: ${{ jobs.repo.outputs.mobile_android_build }}
      mobile_android_build_all:
        value: ${{ jobs.repo.outputs.mobile_android_build_all }}
      mobile_android_tests:
        value: ${{ jobs.repo.outputs.mobile_android_tests }}
      mobile_asan:
        value: ${{ jobs.repo.outputs.mobile_asan }}
      mobile_cc_tests:
        value: ${{ jobs.repo.outputs.mobile_cc_tests }}
      mobile_compile_time_options:
        value: ${{ jobs.repo.outputs.mobile_compile_time_options }}
      mobile_coverage:
        value: ${{ jobs.repo.outputs.mobile_coverage }}
      mobile_formatting:
        value: ${{ jobs.repo.outputs.mobile_formatting }}
      mobile_ios_build:
        value: ${{ jobs.repo.outputs.mobile_ios_build }}
      mobile_ios_build_all:
        value: ${{ jobs.repo.outputs.mobile_ios_build_all }}
      mobile_ios_tests:
        value: ${{ jobs.repo.outputs.mobile_ios_tests }}
      mobile_release_validation:
        value: ${{ jobs.repo.outputs.mobile_release_validation }}
      mobile_tsan:
        value: ${{ jobs.repo.outputs.mobile_tsan }}

      repo_ref:
        value: ${{ jobs.repo.outputs.repo_ref }}
      repo_ref_name:
        value: ${{ jobs.repo.outputs.repo_ref_name }}
      repo_ref_sha:
        value: ${{ jobs.repo.outputs.repo_ref_sha }}
      repo_ref_sha_short:
        value: ${{ jobs.repo.outputs.repo_ref_sha_short }}
      repo_ref_title:
        value: ${{ jobs.repo.outputs.repo_ref_title }}

      trusted:
        value: ${{ jobs.repo.outputs.trusted }}

      version_dev:
        value: ${{ jobs.repo.outputs.version_dev }}
      version_patch:
        value: ${{ jobs.repo.outputs.version_patch }}

concurrency:
  group: |
    ${{ github.actor != 'trigger-release-envoy[bot]'
        && github.event.inputs.head_ref
        || github.run_id
    }}-${{ github.workflow }}-env
  cancel-in-progress: true

jobs:
  repo:
    if: github.repository == 'envoyproxy/envoy'
    runs-on: ubuntu-22.04
    outputs:
      build_image_ubuntu: ${{ steps.env.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile: ${{ steps.env.outputs.build_image_ubuntu_mobile }}
      mobile_android_build: ${{ steps.env.outputs.mobile_android_build }}
      mobile_android_build_all: ${{ steps.env.outputs.mobile_android_build_all }}
      mobile_android_tests: ${{ steps.env.outputs.mobile_android_tests }}
      mobile_asan: ${{ steps.env.outputs.mobile_asan }}
      mobile_cc_tests: ${{ steps.env.outputs.mobile_cc_tests }}
      mobile_compile_time_options: ${{ steps.env.outputs.mobile_compile_time_options }}
      mobile_coverage: ${{ steps.env.outputs.mobile_coverage }}
      mobile_formatting: ${{ steps.env.outputs.mobile_formatting }}
      mobile_ios_build: ${{ steps.env.outputs.mobile_ios_build }}
      mobile_ios_build_all: ${{ steps.env.outputs.mobile_ios_build_all }}
      mobile_ios_tests: ${{ steps.env.outputs.mobile_ios_tests }}
      mobile_release_validation: ${{ steps.env.outputs.mobile_release_validation }}
      mobile_tsan: ${{ steps.env.outputs.mobile_tsan }}
      repo_ref: ${{ steps.env.outputs.repo_ref }}
      repo_ref_name: ${{ steps.env.outputs.repo_ref_name }}
      repo_ref_sha: ${{ steps.env.outputs.repo_ref_sha }}
      repo_ref_sha_short: ${{ steps.env.outputs.repo_ref_sha_short }}
      repo_ref_title: ${{ steps.env.outputs.repo_ref_title }}
      trusted: ${{ steps.env.outputs.trusted }}
      version_dev: ${{ steps.env.outputs.version_dev }}
      version_patch: ${{ steps.env.outputs.version_patch }}
    steps:
    - uses: actions/checkout@v4
      name: Checkout Envoy repository
      with:
        fetch-depth: ${{ ! (inputs.check_mobile_run || ! startsWith(github.event_name, 'pull_request')) && 1 || 0 }}
        # WARNING: This allows untrusted code to run!!!
        #  If this is set, then anything before or after in the job should be regarded as
        #  compromised.
        ref: ${{ startsWith(github.event_name, 'pull_request') && inputs.repo_ref || '' }}

    - uses: ./.github/actions/env
      name: Generate environment variables
      id: env
      with:
        check_mobile_run: ${{ inputs.check_mobile_run }}
        repo_ref: ${{ inputs.repo_ref }}
        repo_ref_name: ${{ inputs.repo_ref_name }}
        repo_ref_sha: ${{ inputs.repo_ref_sha }}
        build_image_repo: ${{ inputs.build_image_repo }}
        build_image_tag: ${{ inputs.build_image_tag }}
        build_image_mobile_sha: ${{ inputs.build_image_mobile_sha }}
        build_image_sha: ${{ inputs.build_image_sha }}

    - name: 'Print env'
      run: |
        echo "version_dev=${{ steps.env.outputs.version_dev }}"
        echo "version_patch=${{ steps.env.outputs.version_patch }}"
        echo "trusted=${{ steps.env.outputs.trusted }}"
        echo "repo_ref=${{ steps.env.outputs.repo_ref }}"
        echo "repo_ref_name=${{ steps.env.outputs.repo_ref_name }}"
        echo "repo_ref_pr_number=${{ steps.env.outputs.repo_ref_pr_number }}"
        echo "repo_ref_sha=${{ steps.env.outputs.repo_ref_sha }}"
        echo "repo_ref_sha_short=${{ steps.env.outputs.repo_ref_sha_short }}"
        echo "repo_ref_title=${{ steps.env.outputs.repo_ref_title }}"
        echo "build_image_ubuntu=${{ steps.env.outputs.build_image_ubuntu }}"
        echo "build_image_ubuntu_mobile=${{ steps.env.outputs.build_image_ubuntu_mobile }}"
        echo
        if [[ -n "${{ steps.env.outputs.repo_ref_pr_number }}" ]]; then
            echo "PR: https://github.com/envoyproxy/envoy/pull/${{ steps.env.outputs.repo_ref_pr_number }}"
        fi

  cache:
    if: ${{ inputs.prime_build_image }}
    uses: ./.github/workflows/_cache_docker.yml
    with:
      image_repo: ${{ inputs.build_image_repo }}
      image_tag: ${{ inputs.build_image_tag }}
      image_sha: ${{ inputs.build_image_sha }}
