name: Precheck/deps

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      dependency-review:
        type: boolean
        default: false
      request:
        type: string
        required: true
      trusted:
        type: boolean
        required: true

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}-deps
  cancel-in-progress: true


jobs:
  deps:
    permissions:
      actions: read
      contents: read
      packages: read
    uses: ./.github/workflows/_run.yml
    name: ${{ matrix.target }}
    with:
      bazel-cache: true
      bazel-extra: '--config=rbe'
      cache-build-image: ${{ fromJSON(inputs.request).request.build-image.default }}
      concurrency-suffix: -${{ matrix.target }}
      request: ${{ inputs.request }}
      error-match: |
        ERROR
        error:
        Error:
      rbe: true
      target: ${{ matrix.target }}
      trusted: ${{ inputs.trusted }}
    strategy:
      matrix:
        include:
        - target: deps

  dependency-review:
    runs-on: ubuntu-24.04
    if: ${{ inputs.dependency-review }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        ref: ${{ fromJSON(inputs.request).request.sha }}
        persist-credentials: false
    - name: Dependency Review
      uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261  # v4.8.2
