name: Precheck/deps

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      dependency-review:
        type: boolean
        default: false
      request:
        type: string
        required: true
      trusted:
        type: boolean
        required: true

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}-publish
  cancel-in-progress: true


jobs:
  prechecks:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_run.yml
    name: ${{ matrix.target }}
    with:
      bazel-extra: '--config=rbe-envoy-engflow'
      cache-build-image: ${{ fromJSON(inputs.request).request.build-image.default }}
      request: ${{ inputs.request }}
      error-match: |
        ERROR
        error:
        Error:
      rbe: ${{ matrix.rbe }}
      target: ${{ matrix.target }}
      trusted: ${{ inputs.trusted }}
    strategy:
      matrix:
        include:
        - target: deps
          rbe: false

  dependency-review:
    runs-on: ubuntu-22.04
    if: ${{ inputs.dependency-review }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633  # v4.1.2
      with:
        ref: ${{ fromJSON(inputs.request).request.sha }}
        persist-credentials: false
    - name: Dependency Review
      uses: actions/dependency-review-action@0fa40c3c10055986a88de3baa0d6ec17c5a894b3  # v4.2.3
