name: Publish

permissions:
  contents: read

# The matrices in this config can be combined once the calling workflow has shifted
# to a `pull_request`/`commit` pattern (ie not `workflow_dispatch`)
#
# For now pre/post submit is split between `publish_ci`/`publish`, the latter running
# only for "trusted" runs and having access to secrets/permissions

on:
  workflow_call:
    inputs:
      trusted:
        type: boolean
        default: false
      build_image_ubuntu:
        type: string
        default: ''
      version_dev:
        type: string
        default: ''
      head_ref:
        type: string
        default: ''
      repo_ref:
        type: string
      sha:
        type: string
    secrets:
      ENVOY_CI_SYNC_APP_ID:
      ENVOY_CI_SYNC_APP_KEY:
      ENVOY_CI_PUBLISH_APP_ID:
      ENVOY_CI_PUBLISH_APP_KEY:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}-publish
  cancel-in-progress: true

jobs:
  publish_ci:
    if: ${{ ! inputs.trusted }}
    name: ${{ matrix.name || matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: publish
          name: github
          run_pre: ./.github/actions/publish/release/setup
          run_pre_with: |
            ref: ${{ inputs.repo_ref }}
            bucket: envoy-pr
          env: |
            export ENVOY_PUBLISH_DRY_RUN=1
            export ENVOY_COMMIT=${{ inputs.sha }}
    uses: ./.github/workflows/_ci.yml
    with:
      target: ${{ matrix.target }}
      rbe: false
      managed: true
      cache_build_image: ${{ inputs.build_image_ubuntu }}
      run_pre: ${{ matrix.run_pre }}
      run_pre_with: ${{ matrix.run_pre_with }}
      env: ${{ matrix.env }}
      trusted: false
      repo_ref: ${{ inputs.repo_ref }}

  publish:
    if: ${{ inputs.trusted }}
    name: ${{ matrix.name || matrix.target }}
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: publish
          name: github
          run_pre: ./.github/actions/publish/release/setup
          run_pre_with: |
            ref: ${{ inputs.repo_ref }}
            bucket: envoy-postsubmit
          env: |
            export ENVOY_COMMIT=${{ inputs.sha }}
            if [[ '${{ inputs.version_dev }}' == 'dev' ]]; then
                export ENVOY_PUBLISH_DRY_RUN=1
            fi
    uses: ./.github/workflows/_ci.yml
    with:
      target: ${{ matrix.target }}
      rbe: false
      managed: true
      cache_build_image: ${{ inputs.build_image_ubuntu }}
      run_pre: ${{ matrix.run_pre }}
      run_pre_with: ${{ matrix.run_pre_with }}
      env: ${{ matrix.env }}
      trusted: true
      repo_ref: ${{ inputs.repo_ref }}
    secrets:
      app_id: ${{ secrets.ENVOY_CI_PUBLISH_APP_ID }}
      app_key: ${{ secrets.ENVOY_CI_PUBLISH_APP_KEY }}

  publish_docs:
    # For normal commits to Envoy main this will trigger an update in the website repo,
    # which will update its envoy dep shas, and rebuild the website for the latest docs
    #
    # For commits that create a release, it instead triggers an update in the archive repo,
    # which builds a static version of the docs for the release and commits it to the archive.
    # In turn the archive repo triggers an update in the website so the new release docs are
    # included in the published site
    if: ${{ inputs.trusted }}
    runs-on: ubuntu-22.04
    needs:
    - publish
    steps:
    - uses: envoyproxy/toolshed/gh-actions/dispatch@actions-v0.0.32
      with:
        app_id: ${{ secrets.ENVOY_CI_SYNC_APP_ID }}
        key: "${{ secrets.ENVOY_CI_SYNC_APP_KEY }}"
        ref: main
        repository: ${{ inputs.version_dev == 'dev' && 'envoyproxy/envoy-website' || 'envoyproxy/archive' }}
        workflow: envoy-sync.yaml
        inputs: |
          commit_sha: ${{ inputs.version_dev == 'dev' && github.sha || '' }}
