name: Verify

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      request:
        type: string
        required: true
      trusted:
        type: boolean
        required: true

concurrency:
  group: >-
    ${{ github.actor != 'trigger-release-envoy[bot]'
        && github.event.inputs.head_ref
        || github.run_id
    }}-${{ github.event.workflow.id }}-verify
  cancel-in-progress: true


jobs:
  verify:
    permissions:
      contents: read
      packages: read
    name: ${{ matrix.name || matrix.target }}
    uses: ./.github/workflows/_run.yml
    with:
      cache-build-image:
      container-command:
      rbe: ${{ matrix.rbe }}
      request: ${{ inputs.request }}
      runs-on: envoy-x64-small
      steps-pre: ${{ matrix.steps-pre }}
      source: ${{ matrix.source }}
      target: ${{ matrix.target }}
      trusted: ${{ inputs.trusted }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: examples
          target: verify_examples
          source: |
            export NO_BUILD_SETUP=1
          rbe: false
          steps-pre: |
            - id: url
              uses: envoyproxy/toolshed/gh-actions/jq@6b3ddd1e42c252d68fb98973760c0ee1943c9c21  # actions-v0.2.20
              with:
                options: -Rr
                input: >-
                  ${{ inputs.trusted
                      && fromJSON(inputs.request).request.sha
                      || fromJSON(inputs.request).request.ref }}
                filter: |
                  .[:7] as $sha
                  | if ${{ inputs.trusted }} then
                      "envoy-postsubmit"
                    else
                      "envoy-pr"
                    end
                  | . as $bucket
                  | "https://storage.googleapis.com/\($bucket)/\($sha)"
            - uses: envoyproxy/toolshed/gh-actions/docker/fetch@6b3ddd1e42c252d68fb98973760c0ee1943c9c21  # actions-v0.2.20
              with:
                url: %{{ steps.url.outputs.value }}/docker/envoy.tar
                variant: dev
            - uses: envoyproxy/toolshed/gh-actions/docker/fetch@6b3ddd1e42c252d68fb98973760c0ee1943c9c21  # actions-v0.2.20
              with:
                url: %{{ steps.url.outputs.value }}/docker/envoy-contrib.tar
                variant: contrib-dev
            - uses: envoyproxy/toolshed/gh-actions/docker/fetch@6b3ddd1e42c252d68fb98973760c0ee1943c9c21  # actions-v0.2.20
              with:
                url: %{{ steps.url.outputs.value }}/docker/envoy-google-vrp.tar
                variant: google-vrp-dev
            - run: docker images | grep envoy
              shell: bash
            - run: |
                # Install expected host packages
                export DEBIAN_FRONTEND=noninteractive
                sudo apt-get -qq update -y
                sudo apt-get -qq install -y --no-install-recommends expect gettext whois
                pip install -r ./.github/workflows/verify-requirements.txt
              shell: bash
