name: Workflow start
# This workflow is only required for externally triggered jobs that need to manually
# set the check status for a commit/PR

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  start:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      statuses: write
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/env
      id: env
      with:
        check-mobile-run: false

    - if: ${{ steps.env.outputs.trusted != 'true' }}
      name: Start status check
      uses: envoyproxy/toolshed/gh-actions/status@actions-v0.1.8
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: ${{ inputs.workflow_name }}
        state: 'pending'
        sha: ${{ inputs.sha }}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    - if: ${{ steps.env.outputs.trusted != 'true' }}
      name: Save the SHA
      env:
        STATE_SHA: ${{ inputs.sha }}
      run: |
        mkdir -p ./sha
        echo $STATE_SHA > ./sha/state_sha
    - if: ${{ steps.env.outputs.trusted != 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: state_sha
        path: sha/
