name: android_tests

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  kotlintestsmac:
    if: github.repository == 'envoyproxy/envoy'
    # revert to //test/kotlin/... once fixed
    # https://github.com/envoyproxy/envoy-mobile/issues/1932
    name: kotlin_tests_mac
    runs-on: macos-12
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Java setup'
      if: steps.should_run.outputs.run_ci_job == 'true'
      uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Kotlin library tests'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/kotlin/io/...
  javatestsmac:
    if: github.repository == 'envoyproxy/envoy'
    name: java_tests_mac
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Java setup'
      if: steps.should_run.outputs.run_ci_job == 'true'
      uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Java library tests'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            --config test-android \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            --define=signal_trace=disabled \
            //test/java/...
  kotlintestslinux:
    if: github.repository == 'envoyproxy/envoy'
    # Only kotlin tests are executed since with linux:
    # https://github.com/envoyproxy/envoy-mobile/issues/1418.
    name: kotlin_tests_linux
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:mobile-458cb49ca2013c0ccf057d00ad1d4407920c4e52
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run Kotlin library integration tests'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            --config test-android \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-clang") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/kotlin/...
