name: android_tests

on:
  push:
    branches:
    - main
    paths:
    - 'mobile/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'mobile/**'
    - '.github/workflows/**'

jobs:
  kotlintestsmac:
    # revert to //test/kotlin/... once fixed
    # https://github.com/envoyproxy/envoy-mobile/issues/1932
    name: kotlin_tests_mac
    runs-on: macos-12
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v1
    - id: check_context
      name: 'Check whether to run'
      run: |
        if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e java/ -e kotlin/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/android_tests.yml$ ; then
            echo "Tests will run."
            echo "run_tests=true" >> $GITHUB_OUTPUT
          else
            echo "Skipping tests."
            echo "run_tests=false" >> $GITHUB_OUTPUT
          fi
    - name: 'Java setup'
      if: steps.check_context.outputs.run_tests == 'true'
      uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      if: steps.check_context.outputs.run_tests == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Kotlin library tests'
      if: steps.check_context.outputs.run_tests == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/kotlin/io/...
  javatestsmac:
    name: java_tests_mac
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v1
    - id: check_context
      name: 'Check whether to run'
      run: |
        if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e java/ -e kotlin/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/android_tests.yml$ ; then
            echo "Tests will run."
            echo "run_tests=true" >> $GITHUB_OUTPUT
          else
            echo "Skipping tests."
            echo "run_tests=false" >> $GITHUB_OUTPUT
          fi
    - name: 'Java setup'
      if: steps.check_context.outputs.run_tests == 'true'
      uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      if: steps.check_context.outputs.run_tests == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Java library tests'
      if: steps.check_context.outputs.run_tests == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            --define=signal_trace=disabled \
            //test/java/...
  kotlintestslinux:
    # Only kotlin tests are executed since with linux:
    # https://github.com/envoyproxy/envoy-mobile/issues/1418.
    name: kotlin_tests_linux
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v1
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: check_context
      name: 'Check whether to run'
      run: |
        if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e java/ -e kotlin/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/android_tests.yml$ ; then
            echo "Tests will run."
            echo "run_tests=true" >> $GITHUB_OUTPUT
          else
            echo "Skipping tests."
            echo "run_tests=false" >> $GITHUB_OUTPUT
          fi
    - name: 'Java setup'
      if: steps.check_context.outputs.run_tests == 'true'
      uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      if: steps.check_context.outputs.run_tests == 'true'
      run: cd mobile && ./ci/linux_ci_setup.sh
    - name: 'Run Kotlin library integration tests'
      if: steps.check_context.outputs.run_tests == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-clang") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/kotlin/...
