name: mobile_cc_tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  cctests:
    name: cc_tests
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    container:
      image: envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446
    steps:
    - uses: actions/checkout@v1
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: 'Run tests'
        # Regression test using the new API listener. TODO(#2711) clean up.
      run: |
        cd mobile && ./bazelw test \
            --action_env=LD_LIBRARY_PATH \
            --test_output=all \
            --copt=-DUSE_API_LISTENER
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/cc/...
