name: Check dependencies

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run dependency checker
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          bazel run //tools/dependency:check -- -c release_issues --fix
          bazel run //tools/dependency:check -- -c cves -w error
