name: Check for latest_release of deps

on :
  schedule :
    - cron : '0 8 * * *'

  workflow_dispatch :

jobs :
  build :
    runs-on : ubuntu-latest
    if: github.repository_owner == 'envoyproxy'

    steps :
      - name : checkout
        uses : actions/checkout/@v2
        with :
          ref : ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: setting up virtualenv
        run : |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          # --create_issues flag to create issue only in github action
          # and not interfere with the CI
          ./tools/dependency/release_dates.sh ./bazel/repository_locations.bzl --create_issues
          ./tools/dependency/release_dates.sh ./api/bazel/repository_locations.bzl --create_issues
