name: Check dependencies

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)
  issues: write # required to open/close dependency issues

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python (3.10)
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: "3.10"

      - name: Run dependency checker
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          TODAY_DATE=$(date -u -I"date")
          export TODAY_DATE
          bazel run //tools/dependency:check --action_env=TODAY_DATE -- -c release_issues --fix
          bazel run //tools/dependency:check --action_env=TODAY_DATE -- -c cves -w error
