name: Check dependencies

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'envoyproxy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0ebf233433c08fb9061af664d501c3f3ff0e9e20 # v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run dependency checker
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          bazel run //tools/dependency:check -- -c release_issues --fix
          bazel run //tools/dependency:check -- -c cves -w error
