name: Check dependencies

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    permissions:
      contents: read # to fetch code (actions/checkout)
      issues: write # required to open/close dependency issues
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python (3.10)
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
        with:
          python-version: "3.10"

      - name: Run dependency checker
        run: |
          TODAY_DATE=$(date -u -I"date")
          export TODAY_DATE
          bazel run //tools/dependency:check --action_env=TODAY_DATE -- -c release_issues --fix
          bazel run //tools/dependency:check --action_env=TODAY_DATE -- -c cves -w error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
