name: CI

on:
  push:
    branches: [ zh ]
  pull_request:
    branches: [ zh ]
    
jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code into the envoy module directory
      uses: actions/checkout@v2
    
    - name: Build
      run: bash ./ci/run_envoy_docker.sh 'docs/build.sh'
      
            
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: 'generated/docs/'
        production-branch: zh
        production-deploy: false
        github-token: ${{ secrets.ENVOY }}
        deploy-message: "${{ github.event.pull_request.title }} Deploy succeeded"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
        alias: deploy-preview-${{ github.event.number }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 5   
    
    - name: Deploy docs with github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY}}
        publish_dir: ./generated/docs