name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@284319451007d5ba938e4afb047f602d7f2cd6c6
