name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@11310527b429536e263dc6cc47873e608189ba21
