name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@2b96ea7f03d82de498e97b42e6bee3f7cb0dafaa
