name: mobile_docs

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    container:
      image: envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Generate docs
      run: mobile/docs/build.sh
    - name: Set up deploy key
      uses: shimataro/ssh-key-action@193316a178ec055fcc7b018f7f76bbf64085c628
      with:
        key: ${{ secrets.ENVOY_MOBILE_WEBSITE_DEPLOY_KEY }}
        known_hosts: unnecessary
    - name: Publish docs
      run: mobile/docs/publish.sh
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: generated/docs
