name: Environment

on:
  workflow_call:
    outputs:
      build_image_ubuntu:
        value: ${{ jobs.repo.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile:
        value: ${{ jobs.repo.outputs.build_image_ubuntu_mobile }}
      mobile_android_build:
        value: ${{ jobs.repo.outputs.mobile_android_build }}
      mobile_android_build_all:
        value: ${{ jobs.repo.outputs.mobile_android_build_all }}
      mobile_android_tests:
        value: ${{ jobs.repo.outputs.mobile_android_tests }}
      mobile_asan:
        value: ${{ jobs.repo.outputs.mobile_asan }}
      mobile_cc_tests:
        value: ${{ jobs.repo.outputs.mobile_cc_tests }}
      mobile_compile_time_options:
        value: ${{ jobs.repo.outputs.mobile_compile_time_options }}
      mobile_coverage:
        value: ${{ jobs.repo.outputs.mobile_coverage }}
      mobile_formatting:
        value: ${{ jobs.repo.outputs.mobile_formatting }}
      mobile_ios_build:
        value: ${{ jobs.repo.outputs.mobile_ios_build }}
      mobile_ios_build_all:
        value: ${{ jobs.repo.outputs.mobile_ios_build_all }}
      mobile_ios_tests:
        value: ${{ jobs.repo.outputs.mobile_ios_tests }}
      mobile_release_validation:
        value: ${{ jobs.repo.outputs.mobile_release_validation }}
      mobile_tsan:
        value: ${{ jobs.repo.outputs.mobile_tsan }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}-env
  cancel-in-progress: true

jobs:
  repo:
    if: github.repository == 'envoyproxy/envoy'
    runs-on: ubuntu-20.04
    outputs:
      build_image_ubuntu: ${{ steps.build_image.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile: ${{ steps.build_image.outputs.build_image_ubuntu_mobile }}
      mobile_android_build: ${{ steps.should_run.outputs.mobile_android_build }}
      mobile_android_build_all: ${{ steps.should_run.outputs.mobile_android_build_all }}
      mobile_android_tests: ${{ steps.should_run.outputs.mobile_android_tests }}
      mobile_asan: ${{ steps.should_run.outputs.mobile_asan }}
      mobile_cc_tests: ${{ steps.should_run.outputs.mobile_cc_tests }}
      mobile_compile_time_options: ${{ steps.should_run.outputs.mobile_compile_time_options }}
      mobile_coverage: ${{ steps.should_run.outputs.mobile_coverage }}
      mobile_formatting: ${{ steps.should_run.outputs.mobile_formatting }}
      mobile_ios_build: ${{ steps.should_run.outputs.mobile_ios_build }}
      mobile_ios_build_all: ${{ steps.should_run.outputs.mobile_ios_build_all }}
      mobile_ios_tests: ${{ steps.should_run.outputs.mobile_ios_tests }}
      mobile_release_validation: ${{ steps.should_run.outputs.mobile_release_validation }}
      mobile_tsan: ${{ steps.should_run.outputs.mobile_tsan }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy

    - id: build_image
      name: 'Check current build images'
      run: |
        {
            echo "build_image_ubuntu=${BUILD_IMAGE_UBUNTU_REPO}:${BUILD_IMAGE_UBUNTU}@sha256:${BUILD_IMAGE_UBUNTU_SHA}"
            echo "build_image_ubuntu_mobile=${BUILD_IMAGE_UBUNTU_REPO}:mobile-${BUILD_IMAGE_UBUNTU}@sha256:${BUILD_IMAGE_UBUNTU_MOBILE_SHA}"
        } >> "$GITHUB_OUTPUT"
      env:
        # TODO(phlax): derive these from a config file
        BUILD_IMAGE_UBUNTU_REPO: envoyproxy/envoy-build-ubuntu
        BUILD_IMAGE_UBUNTU: 105fdc54acc55ff0ff0c5b784d8cfe8dc225aad4
        BUILD_IMAGE_UBUNTU_SHA: 1e89eb7136b4d53b021c52b3497255e6221da8a2003d7c727e397e4ecb227d9b
        BUILD_IMAGE_UBUNTU_MOBILE_SHA: 1e89eb7136b4d53b021c52b3497255e6221da8a2003d7c727e397e4ecb227d9b

    - id: should_run
      name: 'Check what to run'
      run: |
        ./mobile/tools/what_to_run.sh
