name: Envoy/prechecks

permissions:
  contents: read

on:
  push:
    branches:
    - main
    - release/v*
  pull_request_target:
    paths:
    - '**/requirements*.txt'
    - '**/go.mod'
    - '**/*.bzl'
    - 'WORKSPACE'
    - '.github/workflows/envoy-prechecks.yml'
    - '.github/workflows/_*.yml'

concurrency:
  group: ${{ github.event.inputs.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    uses: ./.github/workflows/_env.yml
    with:
      prime_build_image: true
      check_mobile_run: false
    permissions:
      contents: read
      packages: read
      # TODO(phlax): figure out how to remove this
      statuses: write

  prechecks:
    needs:
    - env
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: deps
          rbe: false
          managed: true
    uses: ./.github/workflows/_ci.yml
    name: CI ${{ matrix.target }}
    with:
      target: ${{ matrix.target }}
      rbe: ${{ matrix.rbe }}
      managed: ${{ matrix.managed }}
      cache_build_image: ${{ needs.env.outputs.build_image_ubuntu }}
