name: format

on:
  push:
    branches:
    - main
    paths:
    - 'mobile/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'mobile/**'
    - '.github/workflows/**'

jobs:
  formatall:
    name: format_all
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    container:
      image: envoyproxy/envoy-build-ubuntu:0a02a76af5951bf7f4c7029c0ea6d29d96c0f682
      env:
        CLANG_FORMAT: /opt/llvm/bin/clang-format
        BUILDIFIER_BIN: /usr/local/bin/buildifier
        BUILDOZER_BIN: /usr/local/bin/buildozer
        ENVOY_BAZEL_PREFIX: "@envoy"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: 'Run formatters'
      run: cd mobile && ./tools/check_format.sh
  precommit:
    name: precommit
    runs-on: macos-12
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v1
    - name: 'Install precommit'
      run: brew install pre-commit
    - name: 'Run precommit'
      run: cd mobile && find mobile/* | pre-commit run --files
  swiftlint:
    name: swift_lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: ghcr.io/realm/swiftlint:0.50.1
    steps:
    - uses: actions/checkout@v1
    - name: 'Run Swift Lint (SwiftLint)'
      run: swiftlint lint --strict
      working-directory: mobile
  drstring:
    name: drstring
    runs-on: macos-12
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: 'Run DrString'
      env:
        DEVELOPER_DIR: /Applications/Xcode_14.1.app
      run: cd mobile && ./bazelw run @DrString//:drstring check
  kotlinlint:
    name: kotlin_lint
    runs-on: macos-12
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
    - run: cd mobile && ./ci/mac_ci_setup.sh
      name: 'Install dependencies'
    - name: 'Run Kotlin Lint (Detekt)'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //library/kotlin/io/envoyproxy/envoymobile:envoy_lib_lint \
            //examples/kotlin/hello_world:hello_envoy_kt_lint
    - name: 'Run Kotlin Formatter (ktlint)'
      run: |
        cd mobile && ./bazelw build kotlin_format
