name: mobile_format

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  formatall:
    name: format_all
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    container:
      image: envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446
      env:
        CLANG_FORMAT: /opt/llvm/bin/clang-format
        BUILDIFIER_BIN: /usr/local/bin/buildifier
        BUILDOZER_BIN: /usr/local/bin/buildozer
        ENVOY_BAZEL_PREFIX: "@envoy"
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run formatters'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./tools/check_format.sh
  precommit:
    name: precommit
    runs-on: macos-12
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Install precommit'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: brew install pre-commit
    - name: 'Run precommit'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && find mobile/* | pre-commit run --files
  swiftlint:
    name: swift_lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: ghcr.io/realm/swiftlint:0.50.1
    steps:
    - uses: actions/checkout@v3
    - name: 'Run Swift Lint (SwiftLint)'
      run: swiftlint lint --strict
      working-directory: mobile
  drstring:
    name: drstring
    runs-on: macos-12
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run DrString'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        DEVELOPER_DIR: /Applications/Xcode_14.1.app
      run: cd mobile && ./bazelw run @DrString//:drstring check
  kotlinlint:
    name: kotlin_lint
    runs-on: macos-12
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
      if: steps.should_run.outputs.run_ci_job == 'true'
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - run: cd mobile && ./ci/mac_ci_setup.sh
      if: steps.should_run.outputs.run_ci_job == 'true'
      name: 'Install dependencies'
    - name: 'Run Kotlin Lint (Detekt)'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //library/kotlin/io/envoyproxy/envoymobile:envoy_lib_lint \
            //examples/kotlin/hello_world:hello_envoy_kt_lint
    - name: 'Run Kotlin Formatter (ktlint)'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./bazelw build kotlin_format
