name: ios_build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  iosbuild:
    name: ios_build
    runs-on: macos-12
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw shutdown
          ./bazelw build \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //library/swift:ios_framework
        name: 'Build Envoy.framework distributable'
  swifthelloworld:
    name: swift_helloworld
    needs: iosbuild
    runs-on: macos-12
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw build \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //examples/swift/hello_world:app
        name: 'Build swift app'
      # Run the app in the background and redirect logs.
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw run \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //examples/swift/hello_world:app &> /tmp/envoy.log &
        name: 'Run swift app'
      - run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
        name: 'Check connectivity'
      - run: cat /tmp/envoy.log
        if: ${{ failure() || cancelled() }}
        name: 'Log app run'
  swiftbaselineapp:
    name: swift_baseline_app
    needs: iosbuild
    runs-on: macos-12
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw build \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/swift/apps/baseline:app
        name: 'Build swift app'
      # Run the app in the background and redirect logs.
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw run \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/swift/apps/baseline:app &> /tmp/envoy.log &
        name: 'Run swift app'
      - run: sed '/received headers with status 301/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
        name: 'Check connectivity'
      - run: cat /tmp/envoy.log
        if: ${{ failure() || cancelled() }}
        name: 'Log app run'
  swiftexperimentalapp:
    name: swift_experimental_app
    needs: iosbuild
    runs-on: macos-12
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw build \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/swift/apps/experimental:app
        name: 'Build swift app'
      # Run the app in the background and redirect logs.
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw run \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/swift/apps/experimental:app &> /tmp/envoy.log &
        name: 'Run swift app'
      - run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
        name: 'Check connectivity'
      - run: cat /tmp/envoy.log
        if: ${{ failure() || cancelled() }}
        name: 'Log app run'
  swiftasyncawait:
    name: swift_async_await
    needs: iosbuild
    runs-on: macos-12
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw build \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //examples/swift/async_await:app
        name: 'Build swift app'
      # Run the app in the background and redirect logs.
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw run \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //examples/swift/async_await:app &> /tmp/envoy.log &
        name: 'Run swift app'
      - run: sed '/\[2\] Uploaded 7 MB of data/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
        name: 'Check upload succeeded'
      - run: cat /tmp/envoy.log
        if: ${{ failure() || cancelled() }}
        name: 'Log app run'
  objchelloworld:
    name: objc_helloworld
    needs: iosbuild
    runs-on: macos-12
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw build \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //examples/objective-c/hello_world:app
        name: 'Build objective-c app'
      # Run the app in the background and redirect logs.
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw run \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //examples/objective-c/hello_world:app &> /tmp/envoy.log &
        name: 'Run objective-c app'
      - run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
        name: 'Check connectivity'
      - run: cat /tmp/envoy.log
        if: ${{ failure() || cancelled() }}
        name: 'Log app run'
