name: mobile_coverage

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    uses: ./.github/workflows/env.yml
    secrets: inherit

  coverage:
    if: ${{ needs.env.outputs.mobile_coverage == 'true' }}
    needs: env
    name: coverage
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    container:
      image: envoyproxy/envoy-build-ubuntu:818d28832abf2a7c0cb2bff00435be231729a0bf
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run coverage'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && BAZEL_BUILD_OPTION_LIST="--config=remote-ci-linux-coverage" \
            PATH=/opt/llvm/bin:${PATH} \
            COVERAGE_THRESHOLD=76 \
            ../test/run_envoy_bazel_coverage.sh //test/common/...
    - name: 'Package coverage'
      run: |
        cd mobile && tar -czf coverage.tar.gz generated/coverage
    - name: 'Upload report'
      uses: actions/upload-artifact@v3
      with:
        name: coverage.tar.gz
        path: mobile/coverage.tar.gz
