name: mobile_format

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  formatall:
    if: github.repository == 'envoyproxy/envoy'
    name: format_all
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    container:
      image: envoyproxy/envoy-build-ubuntu:321658b6b50abda6869f89fac275f59bf3b1e757
      env:
        CLANG_FORMAT: /opt/llvm/bin/clang-format
        BUILDIFIER_BIN: /usr/local/bin/buildifier
        BUILDOZER_BIN: /usr/local/bin/buildozer
        ENVOY_BAZEL_PREFIX: "@envoy"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run formatters'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./tools/check_format.sh
  precommit:
    if: github.repository == 'envoyproxy/envoy'
    name: precommit
    runs-on: macos-12
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Install precommit'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: brew install pre-commit
    - name: 'Run precommit'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && find mobile/* | pre-commit run --files
  swiftlint:
    if: github.repository == 'envoyproxy/envoy'
    name: swift_lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: ghcr.io/realm/swiftlint:0.50.3
    steps:
    - uses: actions/checkout@v3
    - name: 'Run Swift Lint (SwiftLint)'
      run: swiftlint lint --strict
      working-directory: mobile
  drstring:
    if: github.repository == 'envoyproxy/envoy'
    name: drstring
    runs-on: macos-12
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run DrString'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        DEVELOPER_DIR: /Applications/Xcode_14.1.app
      run: cd mobile && ./bazelw run @DrString//:drstring check
  kotlinlint:
    if: github.repository == 'envoyproxy/envoy'
    name: kotlin_lint
    runs-on: macos-12
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      if: steps.should_run.outputs.run_ci_job == 'true'
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - run: cd mobile && ./ci/mac_ci_setup.sh
      if: steps.should_run.outputs.run_ci_job == 'true'
      name: 'Install dependencies'
    - name: 'Run Kotlin Lint (Detekt)'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            //library/kotlin/io/envoyproxy/envoymobile:envoy_lib_lint \
            //examples/kotlin/hello_world:hello_envoy_kt_lint
    - name: 'Run Kotlin Formatter (ktlint)'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./bazelw build kotlin_format
