name: mobile_cc_tests

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string

jobs:
  cctests:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run == 'true' }}
    name: cc_tests
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    container:
      image: envoyproxy/envoy-build-ubuntu:818d28832abf2a7c0cb2bff00435be231729a0bf
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: 'Run tests'
        # Regression test using the new API listener. TODO(#2711) clean up.
      run: |
        cd mobile && ./bazelw test \
            --action_env=LD_LIBRARY_PATH \
            --test_output=all \
            --copt=-DUSE_API_LISTENER \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux") \
            //test/cc/...
