name: mobile_docs

on:
  workflow_call:

jobs:
  docs:
    if: github.repository == 'envoyproxy/envoy'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    container:
      image: envoyproxy/envoy-build-ubuntu:818d28832abf2a7c0cb2bff00435be231729a0bf
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Generate docs
      run: mobile/docs/build.sh
    - name: Set up deploy key
      if: github.ref == 'refs/heads/main'
      uses: shimataro/ssh-key-action@v2.5.1
      with:
        key: ${{ secrets.ENVOY_MOBILE_WEBSITE_DEPLOY_KEY }}
        known_hosts: unnecessary
    - name: Publish docs
      if: github.ref == 'refs/heads/main'
      run: mobile/docs/publish.sh
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: generated/docs
