name: android_build

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string
      run_all:
        required: true
        type: string

jobs:
  androidbuild:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run == 'true' }}
    name: android_build
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:mobile-818d28832abf2a7c0cb2bff00435be231729a0bf
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Build envoy.aar distributable'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
          $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-clang") \
          --fat_apk_cpu=x86_64 \
          --linkopt=-fuse-ld=lld \
          //:android_dist

  javahelloworld:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run_all == 'true' }}
    name: java_helloworld
    needs: androidbuild
    runs-on: macos-12
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - run: cd mobile && ./ci/mac_ci_setup.sh --android
      name: 'Install dependencies'
    - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
      name: 'Start emulator'
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: ./mobile/ci/start_android_emulator.sh
    # Return to using:
    #   cd mobile && ./bazelw mobile-install --fat_apk_cpu=x86_64 --start_app //examples/java/hello_world:hello_envoy
    # When https://github.com/envoyproxy/envoy-mobile/issues/853 is fixed.
    - name: 'Start java app'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --fat_apk_cpu=x86_64 \
            //examples/java/hello_world:hello_envoy
          adb install -r --no-incremental bazel-bin/examples/java/hello_world/hello_envoy.apk
          adb shell am start -n io.envoyproxy.envoymobile.helloenvoy/.MainActivity
    - name: 'Check connectivity'
      run: |
        timeout 30 adb logcat -e "received headers with status 301" -m 1 || {
            echo "Failed checking for headers in adb logcat" >&2
            timeout 30 adb logcat || {
                echo "Failed dumping adb logcat" >&2
            }
            exit 1
        }
  kotlinhelloworld:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run == 'true' }}
    name: kotlin_helloworld
    needs: androidbuild
    runs-on: macos-12
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      run: cd mobile && ./ci/mac_ci_setup.sh --android
    - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
      name: 'Start emulator'
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: ./mobile/ci/start_android_emulator.sh
    # Return to using:
    #   ./bazelw mobile-install --fat_apk_cpu=x86_64 --start_app //examples/kotlin/hello_world:hello_envoy_kt
    # When https://github.com/envoyproxy/envoy-mobile/issues/853 is fixed.
    - name: 'Start kotlin app'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --fat_apk_cpu=x86_64 \
            //examples/kotlin/hello_world:hello_envoy_kt
          adb install -r --no-incremental bazel-bin/examples/kotlin/hello_world/hello_envoy_kt.apk
          adb shell am start -n io.envoyproxy.envoymobile.helloenvoykotlin/.MainActivity
    - name: 'Check connectivity'
      run: |
        timeout 30 adb logcat -e "received headers with status 200" -m 1 || {
            echo "Failed checking for headers in adb logcat" >&2
            timeout 30 adb logcat || {
                echo "Failed dumping adb logcat" >&2
            }
            exit 1
        }

  kotlinbaselineapp:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run_all == 'true' }}
    name: kotlin_baseline_app
    needs: androidbuild
    runs-on: macos-12
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      run: cd mobile && ./ci/mac_ci_setup.sh --android
    - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
      name: 'Start emulator'
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: ./mobile/ci/start_android_emulator.sh
    # Return to using:
    #   ./bazelw mobile-install --fat_apk_cpu=x86_64 --start_app //examples/kotlin/hello_world:hello_envoy_kt
    # When https://github.com/envoyproxy/envoy-mobile/issues/853 is fixed.
    - name: 'Start kotlin app'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --fat_apk_cpu=x86_64 \
            //test/kotlin/apps/baseline:hello_envoy_kt
          adb install -r --no-incremental bazel-bin/test/kotlin/apps/baseline/hello_envoy_kt.apk
          adb shell am start -n io.envoyproxy.envoymobile.helloenvoybaselinetest/.MainActivity
    - name: 'Check connectivity'
      run: |
        timeout 30 adb logcat -e "received headers with status 301" -m 1 || {
            echo "Failed checking for headers in adb logcat" >&2
            timeout 30 adb logcat || {
                echo "Failed dumping adb logcat" >&2
            }
            exit 1
        }
  kotlinexperimentalapp:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run_all == 'true' }}
    name: kotlin_experimental_app
    needs: androidbuild
    runs-on: macos-12
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      run: cd mobile && ./ci/mac_ci_setup.sh --android
    - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
      name: 'Start emulator'
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: ./mobile/ci/start_android_emulator.sh
    # Return to using:
    #   ./bazelw mobile-install --fat_apk_cpu=x86_64 --start_app //examples/kotlin/hello_world:hello_envoy_kt
    # When https://github.com/envoyproxy/envoy-mobile/issues/853 is fixed.
    - name: 'Start kotlin app'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --fat_apk_cpu=x86_64 \
            --define=admin_functionality=enabled \
            --define envoy_mobile_listener=enabled \
            //test/kotlin/apps/experimental:hello_envoy_kt
          adb install -r --no-incremental bazel-bin/test/kotlin/apps/experimental/hello_envoy_kt.apk
          adb shell am start -n io.envoyproxy.envoymobile.helloenvoyexperimentaltest/.MainActivity
    - name: 'Check connectivity'
      run: |
        timeout 30 adb logcat -e "received headers with status 200" -m 1 || {
            echo "Failed checking for headers in adb logcat" >&2
            timeout 30 adb logcat || {
                echo "Failed dumping adb logcat" >&2
            }
            exit 1
        }
