name: mobile_traffic_director

permissions:
  contents: read

on:
  schedule:
  # Once a day at midnight.
  - cron: '0 0 * * *'
  # Allows manual triggering in the UI. Makes it easier to test.
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-github.workflow
  cancel-in-progress: true

jobs:
  cc_test:
    if: >-
      ${{
          github.repository == 'envoyproxy/envoy'
          && (github.event.schedule
              || !contains(github.actor, '[bot]'))
      }}
    name: cc_test
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run GcpTrafficDirectorIntegrationTest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GCP_TEST_PROJECT_PROD_API_KEY: ${{ secrets.GCP_TEST_PROJECT_PROD_API_KEY }}
        # TODO(abeyad): remove this key once we're fully switched over to using the
        # prod consumer mesh shard.
        GCP_TEST_PROJECT_API_KEY: ${{ secrets.GCP_TEST_PROJECT_API_KEY }}
        ENVOY_IP_TEST_VERSIONS: v4only
      run: |
        cd mobile
        ./bazelw run \
            --config=mobile-remote-ci \
            --config=ci \
            //test/non_hermetic:gcp_traffic_director_integration_test
