name: mobile_tsan

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string

jobs:
  tsan:
    if: ${{ github.repository == 'envoyproxy/envoy' && inputs.run == 'true' }}
    name: tsan
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:mobile-818d28832abf2a7c0cb2bff00435be231729a0bf
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-tsan") \
            //test/common/...
