name: Mobile/iOS build

permissions:
  contents: read

on:
  workflow_run:
    workflows:
    - Request
    types:
    - completed

concurrency:
  group: >-
    ${{ ((github.event.workflow_run.head_branch == 'main'
          || startsWith(github.event.workflow_run.head_branch, 'release/v'))
          && github.event.repository.full_name == github.repository)
        && github.run_id
        || github.event.workflow_run.head_branch }}-${{ github.event.repository.full_name }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  load:
    secrets:
      app-key: ${{ secrets.ENVOY_CI_APP_KEY }}
      app-id: ${{ secrets.ENVOY_CI_APP_ID }}
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
    if: |
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.repository.full_name == github.repository
      && contains(fromJSON('["pull_request_target", "push", "schedule"]'), github.event.workflow_run.event)
    uses: ./.github/workflows/_load.yml
    with:
      check-name: mobile-ios

  build:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_run.yml
    if: ${{ needs.load.outputs.request && fromJSON(needs.load.outputs.request).run.mobile-ios }}
    needs: load
    name: ios-build
    with:
      args: ${{ matrix.args }}
      bind-mount: false
      command: ./bazelw
      container-command:
      docker-ipv6: false
      request: ${{ needs.load.outputs.request }}
      runs-on: macos-15
      source: |
        source ./ci/mac_ci_setup.sh
        ./bazelw shutdown
      steps-post: ${{ matrix.steps-post }}
      target: ${{ matrix.target }}
      timeout-minutes: ${{ matrix.timeout-minutes }}
      trusted: ${{ needs.load.outputs.trusted && fromJSON(needs.load.outputs.trusted) || false }}
      working-directory: mobile
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Build Envoy.framework distributable
          args: >-
            build
            --config=mobile-remote-ci-macos-ios
            //library/swift:ios_framework
          target: ios
          timeout-minutes: 120

  # hello-world:
  #   permissions:
  #     contents: read
  #     packages: read
  #   uses: ./.github/workflows/_run.yml
  #   if: ${{ needs.load.outputs.request && fromJSON(needs.load.outputs.request).run.mobile-ios }}
  #   needs:
  #   - load
  #   - build
  #   name: ios-hello-world
  #   with:
  #     args: >-
  #       build
  #       ${{ matrix.args || '--config=mobile-remote-ci-macos-ios' }}
  #       ${{ matrix.app }}
  #     command: ./bazelw
  #     container-command:
  #     docker-ipv6: false
  #     request: ${{ needs.load.outputs.request }}
  #     runs-on: macos-15
  #     source: |
  #       source ./ci/mac_ci_setup.sh
  #       ./bazelw shutdown
  #     steps-post: |
  #       - uses: envoyproxy/toolshed/gh-actions/envoy/ios/post@actions-v0.3.29
  #         with:
  #           app: ${{ matrix.app }}
  #           args: ${{ matrix.args || '--config=mobile-remote-ci-macos-ios' }}
  #           expected: received headers with status ${{ matrix.expected-status }}
  #         env:
  #           ANDROID_NDK_HOME:
  #           ANDROID_HOME:
  #     target: ${{ matrix.target }}
  #     timeout-minutes: ${{ matrix.timeout-minutes }}
  #     trusted: ${{ needs.load.outputs.trusted && fromJSON(needs.load.outputs.trusted) || false }}
  #     working-directory: mobile
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #       - name: Build swift hello world
  #         app: //examples/swift/hello_world:app
  #         expected-status: 200
  #         target: swift-hello-world
  #         timeout-minutes: 90

  # apps:
  #   permissions:
  #     contents: read
  #     packages: read
  #   uses: ./.github/workflows/_run.yml
  #   if: ${{ needs.load.outputs.request && fromJSON(needs.load.outputs.request).run.mobile-ios-all }}
  #   needs:
  #   - load
  #   - build
  #   name: ios-apps
  #   with:
  #     args: >-
  #       build
  #       ${{ matrix.args || '--config=mobile-remote-ci-macos-ios' }}
  #       ${{ matrix.app }}
  #     command: ./bazelw
  #     container-command:
  #     docker-ipv6: false
  #     request: ${{ needs.load.outputs.request }}
  #     runs-on: macos-15
  #     source: |
  #       source ./ci/mac_ci_setup.sh
  #     steps-post: |
  #       - uses: envoyproxy/toolshed/gh-actions/envoy/ios/post@actions-v0.3.29
  #         with:
  #           app: ${{ matrix.app }}
  #           args: ${{ matrix.args || '--config=mobile-remote-ci-macos-ios' }}
  #           expected: >-
  #             ${{ matrix.expected
  #                 || format('received headers with status {0}', matrix.expected-status) }}
  #           timeout: ${{ matrix.timeout || '5m' }}
  #         env:
  #           ANDROID_NDK_HOME:
  #           ANDROID_HOME:
  #     target: ${{ matrix.target }}
  #     timeout-minutes: 90
  #     trusted: ${{ needs.load.outputs.trusted && fromJSON(needs.load.outputs.trusted) || false }}
  #     working-directory: mobile
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #       - name: Build swift experimental app
  #         args: >-
  #           --config=mobile-remote-ci-macos-ios
  #         app: //test/swift/apps/experimental:app
  #         expected-status: 200
  #         target: swift-experimental-app

  request:
    secrets:
      app-id: ${{ secrets.ENVOY_CI_APP_ID }}
      app-key: ${{ secrets.ENVOY_CI_APP_KEY }}
    permissions:
      actions: read
      contents: read
      pull-requests: read
    if: |
      always()
      && github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.repository.full_name == github.repository
      && contains(fromJSON('["pull_request_target", "push", "schedule"]'), github.event.workflow_run.event)
      && needs.load.outputs.request
      && fromJSON(needs.load.outputs.request).run.mobile-ios
    needs:
    - load
    - build
    # - hello-world
    # - apps
    uses: ./.github/workflows/_finish.yml
    with:
      needs: ${{ toJSON(needs) }}
