name: android_tests

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    uses: ./.github/workflows/env.yml
    secrets: inherit

  kotlintestsmac:
    if: ${{ needs.env.outputs.mobile_android_tests == 'true' }}
    needs: env
    # revert to //test/kotlin/... once fixed
    # https://github.com/envoyproxy/envoy-mobile/issues/1932
    name: kotlin_tests_mac
    runs-on: macos-12
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v3
    - name: 'Java setup'
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Kotlin library tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --define=signal_trace=disabled \
            //test/kotlin/io/...
  javatestsmac:
    if: ${{ needs.env.outputs.mobile_android_tests == 'true' }}
    needs: env
    name: java_tests_mac
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - name: 'Java setup'
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
        distribution: zulu
    - name: 'Install dependencies'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Java library tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            --config test-android \
            --define envoy_mobile_listener=enabled \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --define=signal_trace=disabled \
            --define=system-helper=android \
            //test/java/...
  kotlintestslinux:
    if: ${{ needs.env.outputs.mobile_android_tests == 'true' }}
    needs: env
    # Only kotlin tests are executed since with linux:
    # https://github.com/envoyproxy/envoy-mobile/issues/1418.
    name: kotlin_tests_linux
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:mobile-818d28832abf2a7c0cb2bff00435be231729a0bf
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run Kotlin library integration tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --build_tests_only \
            --config test-android \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-clang") \
            --define=signal_trace=disabled \
            //test/kotlin/...
