name: mobile_docs

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    if: github.repository == 'envoyproxy/envoy'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    container:
      image: envoyproxy/envoy-build-ubuntu:458cb49ca2013c0ccf057d00ad1d4407920c4e52
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Generate docs
      run: mobile/docs/build.sh
    - name: Set up deploy key
      if: github.ref == 'refs/heads/main'
      uses: shimataro/ssh-key-action@f5671c022c18d961309db152cb22c47811096060
      with:
        key: ${{ secrets.ENVOY_MOBILE_WEBSITE_DEPLOY_KEY }}
        known_hosts: unnecessary
    - name: Publish docs
      if: github.ref == 'refs/heads/main'
      run: mobile/docs/publish.sh
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: generated/docs
