name: mobile_coverage

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  coverage:
    if: github.repository == 'envoyproxy/envoy'
    name: coverage
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    container:
      image: envoyproxy/envoy-build-ubuntu:41c5a05d708972d703661b702a63ef5060125c33
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run coverage'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && BAZEL_BUILD_OPTION_LIST="--config=remote-ci-linux-coverage" \
            PATH=/opt/llvm/bin:${PATH} \
            COVERAGE_THRESHOLD=76 \
            ../test/run_envoy_bazel_coverage.sh //test/common/... //test/cc/...
    - name: 'Package coverage'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: |
        cd mobile && tar -czf coverage.tar.gz generated/coverage
    - name: 'Upload report'
      if: steps.should_run.outputs.run_ci_job == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: coverage.tar.gz
        path: mobile/coverage.tar.gz
