name: mobile_perf

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  sizecurrent:
    name: size_current
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    container:
      image: envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v1
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Build test binary'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            --config=sizeopt \
            --config=remote-ci-linux-clang \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/performance:test_binary_size
    - uses: actions/upload-artifact@v3
      with:
        name: sizecurrent
        path: mobile/bazel-bin/test/performance/test_binary_size
  sizemain:
    name: size_main
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v1
    - name: Add safe directory
      run: |
        git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Build test binary'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout main && git pull origin main
          cd mobile && ./bazelw build \
            --config=sizeopt \
            --config=remote-ci-linux-clang \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/performance:test_binary_size
    - uses: actions/upload-artifact@v3
      with:
        name: sizemain
        path: mobile/bazel-bin/test/performance/test_binary_size
  sizecompare:
    name: size_compare
    needs: [sizecurrent, sizemain]
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    container:
      image: envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v3
      with:
        name: sizecurrent
        path: dist/sizecurrent
    - uses: actions/download-artifact@v3
      with:
        name: sizemain
        path: dist/sizemain
    - name: 'Strip and Zip binary'
      run: |
        ls -lh dist/
        strip -s -o dist/main.stripped dist/sizemain/test_binary_size
        strip -s -o dist/current.stripped dist/sizecurrent/test_binary_size
        zip -9 dist/main.zip dist/main.stripped
        zip -9 dist/current.zip dist/current.stripped
    - name: 'Test size regression'
      run: cd mobile && ./ci/test_size_regression.sh dist/main.zip dist/current.zip
