on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * 1,2,3,4,5'

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  pr_notifier:
    permissions:
      contents: read  # to fetch code (actions/checkout)
      statuses: read  # for pr_notifier.py
      pull-requests: read  # for pr_notifier.py
    name: PR Notifier
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/actions/pr_notifier/requirements.txt
    - name: Notify about PRs
      run: python ./.github/actions/pr_notifier/pr_notifier.py --cron_job
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
