on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  prune_stale:
    name: Prune Stale
    runs-on: ubuntu-latest

    steps:
    - name: Prune Stale
      uses: actions/stale@v3.0.15
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 30
        days-before-issue-close: 7
        days-before-pr-stale: 10
        days-before-pr-close: 4
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had activity in the
          last 30 days. It will be closed in the next 7 days unless it is tagged "help wanted" or "no stalebot" or other activity
          occurs. Thank you for your contributions.
        close-issue-message: >
          This issue has been automatically closed because it has not had activity in the
          last 37 days. If this issue is still valid, please ping a maintainer and ask them to label it as "help wanted" or "no stalebot".
          Thank you for your contributions.
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not had
          activity in the last 10 days. It will be closed in 4 days if no further activity occurs. Please
          feel free to give a status update now, ping for review, or re-open when it's ready.
          Thank you for your contributions!
        close-pr-message: >
          This pull request has been automatically closed because it has not had
          activity in the last 14 days. Please feel free to give a status update now, ping for review, or re-open when it's ready.
          Thank you for your contributions!
        stale-issue-label: 'stale'
        exempt-issue-labels: 'no stalebot,help wanted'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'no stalebot'
        operations-per-run: 500
        ascending: true
