name: mobile_tsan

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  tsan:
    name: tsan
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu:dce0a8c5ae9bed54dbcd1349d4333c325a7501cd
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v1
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-tsan") \
            //test/common/...
