name: Workflow complete
# This workflow is only required for externally triggered jobs that have manually
# set the check status for a commit/PR

permissions:
  contents: read

on:
  # Do not run untrusted code here
  workflow_run:
    workflows:
    - Publish & verify
    types:
    - completed

jobs:
  complete:
    if: ${{ github.actor == 'trigger-workflow-envoy[bot]' }}
    runs-on: ubuntu-22.04
    permissions:
      statuses: write
    steps:
    - name: 'Download artifact'
      uses: actions/github-script@v6
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "state_sha"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/state_sha.zip`, Buffer.from(download.data));

    - run: |
        set -e
        unzip state_sha.zip
        STATE_SHA="$(cat state_sha)"
        echo "state_sha=$STATE_SHA" >> "$GITHUB_OUTPUT"
        STATE="${{ github.event.workflow_run.conclusion }}"
        if [[ ${STATE} != "success" ]]; then
            STATE=failure
        fi
        echo "state=${STATE}" >> "$GITHUB_OUTPUT"
      id: job
    - name: Complete status check
      uses: envoyproxy/toolshed/gh-actions/status@actions-v0.0.27
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: Verify/examples
        state: ${{ steps.job.outputs.state }}
        sha: ${{ steps.job.outputs.state_sha }}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
