name: Workflow start
# This workflow is only required for externally triggered jobs that need to manually
# set the check status for a commit/PR

on:
  workflow_call:
    inputs:
      workflowName:
        required: true
        type: string

permissions:
  contents: read

jobs:
  start:
    runs-on: ubuntu-20.04
    permissions:
      statuses: write
    steps:
    - name: Start status check
      uses: envoyproxy/toolshed/gh-actions/status@550585367f05177a3d4193bf1410e7b6a26142cd
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: ${{ inputs.workflowName }}
        state: 'pending'
        sha: ${{ inputs.sha }}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    - name: Save the SHA
      env:
        STATE_SHA: ${{ inputs.sha }}
      run: |
        mkdir -p ./sha
        echo $STATE_SHA > ./sha/state_sha
    - uses: actions/upload-artifact@v3
      with:
        name: state_sha
        path: sha/
